# run: conda env create --file environment.yml
name: mrcnn
dependencies:
  - Pillow
  - cython
  - matplotlib
  - tensorflow>=1.3.0
  - keras>=2.0.8
  - h5py
  - imgaug
  - IPython[all]
  - python=3.7
  - matplotlib>=1.5
  - numpy>=1.11
  - pandas
  - python-dateutil
  - scipy
  - scikit-image
  - plotnine
  - nb_conda
  - opencv<4, >=3.4
  - plantcv
channels:
  - defaults
  - conda-forge
